- name: Create users from CSV
  hosts: all
  become: yes
  tasks:
    - name: Read user data from CSV
      set_fact:
        users_list: "{{ lookup('file', 'users.csv') | split('\n') | map('split', ',') | list }}"
    - name: Create functional users from CSV data
      user:
        name: "{{ item[0] }}"
        comment: "{{ item[1] }},member of {{ item[2] }}"
        generate_ssh_key: yes
        state: present
      when: item[3] | default(false) and not item[4] | default(false)
      loop: "{{ users_list[:] }}"
    
    - name: Copy authorized key
      authorized_key:
        user: "{{ item[0] }}"
        state: present
        key: "{{ lookup('file', '/home/{{ item[0] }}/.ssh/id_rsa.pub') }}"
      when: item[3] | default(false) and not item[4] | default(false)
      loop: "{{ users_list[:] }}"
